runtime: nodejs16
env_variables:
  NODE_ENV: production
  # Add any other environment variables required by your app

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

  # Add any other specific URL handlers or configurations if needed